version: '3'

services:
  bmc-wordpress:
    container_name: bmc-wordpress
    image: wordpress:fpm-alpine
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    networks:
      - bmc-network
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('FORCE_SSL_ADMIN', true);
        if ( isset( $$_SERVER['HTTP_X_FORWARDED_PROTO'] ) && strpos( $$_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false ) {
          $$_SERVER['HTTPS']='on';
        }

  bmc-nginx:
    container_name: bmc-nginx
    depends_on:
      - bmc-wordpress
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - wordpress:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - bmc-network

  bmc-certbot:
    container_name: bmc-certbot
    depends_on:
      - bmc-nginx
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email adelgado0723@gmail.com --agree-tos --no-eff-email --staging -d belleviewmicrogreens.com -d www.belleviewmicrogreens.com

volumes:
  certbot-etc:
  wordpress:

networks:
  bmc-network:
    driver: bridge
